/*types.h*/
#ifndef TYPES__H
#define TYPES__H

typedef enum 
{	
ST_OK,
ST_ERROR_NULL_POINTER,
ST_ERROR_READ,
ST_ERROR_NO_MEM,
ST_ERROR_GET_USER,
ST_ERROR_INSERT,
ST_ERROR_INVALID_IDENTIFIER,
ST_ERROR_INVALID_OPTION,
ST_ERROR_ADD_USER,
ST_EOF,
ST_ERROR_INVALID_DATE,
ST_ERROR_INVALID_DATE_RANGE,
ST_ERROR_OPEN_FILE,
ST_ERROR_CREATE_FILE,
ST_ERROR_INVALID_ARGUMENTS,
ST_ERROR_PRINT,
ST_ERROR_PRINT_NET,
ST_ERROR_INVALID_MSG_ID,
ST_ERROR_INVALID_ID,
ST_ERROR_INVALID_USERNAME,
ST_ERROR_INVALID_FRIENDS,
ST_ERROR_INVALID_MESSAGE,
ST_ERROR_CLA_MIN_ARGUMENTS,
ST_ERROR_MIN_FILES,
ST_ERROR_INVALID_CLA_ID_OPTION,
ST_ERROR_INVALID_CLA_USER_OPTION,
ST_ERROR_INVALID_CLA_OUTPUT_OPTION,
ST_ERROR_INVALID_CLA_OPTION,
ST_ERROR_INITIALIZE_NET
}status_t;

#endif
